# Generated by Django 4.2.9 on 2024-04-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('job_category', models.CharField(max_length=500)),
                ('cv_cover_letter', models.FileField(upload_to='cv_cover_letters/')),
                ('privacy_agreement', models.BooleanField(default=False)),
            ],
        ),
    ]
